Demo Application
elementary/portals pull request #24
Opened 2021-10-20 08:42 UTC by marbetschar

This PR adds a demo application which should allow us to easily test portal implementations. To begin with, this demo app supports the AppChooser portal.

![Screenshot from 2021-10-20 08 42 59](https://user-images.githubusercontent.com/392542/138059643-64ef9e05-0a31-46de-b06c-fcffa01431de.png)

2021-10-20 20:50 UTC, danirabbit commented
I don't think there's any meaningful difference between the way the API is used for text, image, or PDF files so I'm not sure we really need to have different tests for those

2021-10-21 08:26 UTC, marbetschar commented
My intention was to be able to test different files - but yeah, we can just keep one.

2021-10-31 10:36 UTC, marbetschar commented
@danrabbit anything we should address or can this be merged? Would love to build upon this in https://github.com/elementary/portals/pull/20

2021-11-03 12:47 UTC, jeremypw requested changes
When installed (see comment about `yml` path in README.md) this launched the text file in the default app when the button was clicked and only one applicable app was installed (expected).  On installing another text editor a choice dialog was shown (expected). However, on closing that text editor and clicking "Open Text" button again, no dialog appeared - it was hidden below the demo window.  Need to make sure the dialog is always presented.

Otherwise looking good,

2021-11-03 12:47 UTC, jeremypw commented on demo/README.md
> +    flatpak-builder build io.elementary.portals.demo.yml --user --install --force-clean
The path to the `yml` file needs to be `demo/io.elementary.portals.demo.yml` if you are in the root directory.

2021-11-11 12:54 UTC, marbetschar commented
any ideas why the dialog appears behind the second time? I mean, the demo app just fires off the portal - but has no clue about it otherwise. So I'm tempted to claim the error lies somewhere else?

Regarding the path to the `yml` file: The basic idea was to force the user to cd into the demo subfolder, to avoid accidents - but I'm fine with either way.

2021-11-13 19:55 UTC, Marukesu commented
I believe we should be using libportal here, so we can have more control of the parameters passed to the portal.

2021-11-15 07:49 UTC, marbetschar commented
@Marukesu don't have any experience with libportal yet - but sound like a great idea! Not sure, if we should address this in a subsequent PR though. Is there any documentation and/or Vala bindings available for libportal?

2021-11-16 22:59 UTC, danrabbit commented
Speaking of libportal, it looks like they already provide a test app for gtk3 and gtk4: https://github.com/flatpak/libportal

Does it make sense to have our own portal test app when one exists?

2021-11-17 11:16 UTC, marbetschar commented
@danirabbit the motivation to build a test app was primarily https://github.com/elementary/portals/pull/20, because I need a way for testing the credentials portal during development.

So I'd claim it makes sense to roll our own test app - but probably only for custom portals such as this "Online Accounts Credentials Provider Portal" thingy...?

2026-01-29 21:52 UTC, danirabbit commented
I'm going to close this since ASHPD exists and this hasn't had any movement in a few years. We can probably introduce a portal tester app if we have platform specific portal backends in the future

2026-01-29 21:52 UTC, closed without merging